### ISSUE TITLE
Doesn't work with select2 v4

### ISSUE THREAD

**Issue by zenzei** [wasikuss/select2-multi-checkboxes#1]
Hi @wasikuss and @kutny. Was checking your plugin and it seems really useful! But as i see in the example (https://jsfiddle.net/wasikuss/gx93rwnk/) only works with the old select2 (v3.5.2). 
Did you ever got it working on the last select2 v4.0.3?
Thanks in advance

**Comment by wasikuss** [comment]
Give me 2-3 days ;) I'll create separate branch to support both v3 and v4 and you will be informed.

**Comment by zenzei** [comment]
Hi @wasikuss, sorry to bother again. Did you manage to test the code to see if can work with v4?
Thanks!

**Comment by zenzei** [comment]
Hi @wasikuss, sorry to ask again, just want to know if you got this working for v4 or if I can help. Thanks!

**Comment by lvmajor** [comment]
Any update on this issue?

**Comment by wasikuss** [comment]
Updated plugin to be compatible with Select2 4.0.3.
