### ISSUE TITLE
On hover, the first selected option is shown as title

### ISSUE THREAD

**Issue by frzsombor** [wasikuss/select2-multi-checkboxes#15]
On hover, the first selected option is shown.
Instead, I think title should be a list of selected options, or the same as the rendered text (or nothing).
![image](https://user-images.githubusercontent.com/7306657/35221264-d102fdda-ff79-11e7-9556-1b922bf1f26a.png)

**Comment by wasikuss** [comment]
fixed in [amd branch](https://github.com/wasikuss/select2-multi-checkboxes/tree/amd). Now it displays same text as rendered in input.
