### ISSUE TITLE
'width' option not working

### ISSUE THREAD

**Issue by frzsombor** [wasikuss/select2-multi-checkboxes#16]
When I try to add `width: '100%'` as an option, it's not getting applied.
You can see it in the [demo JSFiddle](https://jsfiddle.net/wasikuss/7ak9skbb/), first and last select should be 100%, but `width` is only applied to the last one (the original).

**Comment by wasikuss** [comment]
if you're using select2 v4.x please go to [amd branch](https://github.com/wasikuss/select2-multi-checkboxes/tree/amd) - `width` is working correctly there. Code was refactored to conform to official select2 documentation about extensions.

**Comment by evlo** [comment]
can you please provide maybe, even just for me, builded amd branch? Or provide normal compiled .js for amd branch or something for people not using amd?
