### ISSUE TITLE
Using select2-multi-checkboxes with RequireJS

### ISSUE THREAD

**Issue by andrei572** [wasikuss/select2-multi-checkboxes#18]
Great plugin! However, when I try using it on page that (for reasons beyond my control) has to use RequireJS for module loading, it blows up.

What is the correct way of loading the plugin with RequireJS? Do I have to shim any deps?

**Comment by wasikuss** [comment]
If you use select2 4.x, then until end of weekend I'll provide correct implementation using Adapters. It's official way to extend/change behavior of select2. So after update it will work without problems.

**Comment by andrei572** [comment]
Thanks!

**Comment by wasikuss** [comment]
Hey, take a dive into `amd` branch. It adds support for AMD via select2 interface and RequireJS.

https://github.com/wasikuss/select2-multi-checkboxes/tree/amd
