### ISSUE TITLE
expand on load? have it always expanded? and bug with many items.

### ISSUE THREAD

**Issue by daonsh** [wasikuss/select2-multi-checkboxes#2]
is it possible to have it expand the list on load?
And even better, have it always expanded.

Also, when I have lots of items (500), the scroller is displayed and allowed to scoll, but there are checkboxes down below the scroll area (see image).
![select2bug](https://cloud.githubusercontent.com/assets/15046011/25770609/996374e0-3242-11e7-8bca-c25e72b58cca.png)

It'd be better also if it's possible to just have the whole list shown all the time (without an inside scrollbar).

Thanks

**Comment by SeifertDaniel** [comment]
You can fix the "many items issue" with the following pure CSS

        .select2-results__group,
        .select2-results__option[role=treeitem] {
            text-indent: -15px;
            padding-left: 20px !important;
        }

        .select2-results__option .wrap:before{
            position:relative;
            left:-12px;
            font-family:fontAwesome;
            color:#999;
            width:27px;
            height:25px;
        }
        .select2-results__option[role=treeitem] .wrap:before{
            content:"\f096";
        }
        .select2-results__option[aria-selected=true] .wrap:before{
            content:"\f14a";
        }
        .select2-results__option .wrap{
            margin-left:15px;
        }

It fix the unusable checkbox icon on optgroup elements too.

**Comment by wasikuss** [comment]
fixed with new css. take a look into https://jsfiddle.net/wasikuss/7ak9skbb/
