### ISSUE TITLE
Doesn't work with select2 v.4.0.6

### ISSUE THREAD

**Issue by librisius** [wasikuss/select2-multi-checkboxes#22]

**Comment by guillaumepn** [comment]
Same here, I switched to version 4.0.3 in cdn url, as it is the version used on this jsfiddle : https://jsfiddle.net/wasikuss/7ak9skbb/

**Comment by prij** [comment]
I have a patch for 4.0.6-rc.1 here:
https://github.com/prij/select2-multi-checkboxes/commit/3ffe044da83a0c1e8daef82568797811c47412e3#diff-b198f2bcf63152df67a84c5056b556f5

**Comment by wasikuss** [comment]
fixed in #25
