### ISSUE TITLE
Doesn't work when loading data from the server

### ISSUE THREAD

**Issue by oscarlagattaexec** [wasikuss/select2-multi-checkboxes#5]
Is there any example when you have this version working with Ajax server side calls? once I changed my working version to use the check box version then it blocks the input I use to search.

**Comment by s0By** [comment]
Also interested in this. Does the solution work with ajax? and Is it possible to have a search box, otherwise gonna be hard to use with ajax solution due to big amount of options

**Comment by sharmashubhi5** [comment]
Any updates, on how can we load options using select2 ajax feature?

**Comment by wasikuss** [comment]
Loading results from ajax already works, but deselecting not. It's quite hard due to original select2 is not consistent in behavior when using ajax or not. clicking on already selected option won't remove it https://jsfiddle.net/wasikuss/bzrdx5u8. I'am already working on workaround.

**Comment by wasikuss** [comment]
It seems that if `id` is `string` then ajax works normally. Only `templateSelection` fails on getting total items. 
![image](https://user-images.githubusercontent.com/9192409/41422044-600658f8-6ff8-11e8-9b95-f7a4caafa10a.png)

**Comment by sharmashubhi5** [comment]
Yeah, i was able to make it work by using string as ids. Thanks for the response.
