### ISSUE TITLE
lot of options breaks the layout

### ISSUE THREAD

**Issue by Aashishkmr** [wasikuss/select2-multi-checkboxes#6]
https://jsfiddle.net/0afuq7pk/ if u follow this fiddle you will find out that when large number of options are available this just breaks the layout of checkboxes.

This can be fixed if we remove position:absolute from the css for this class .select2-result-label .wrap:before but not sure if this will hamper something else. Please review

**Comment by wasikuss** [comment]
fixed with new css. take a look into https://jsfiddle.net/wasikuss/7ak9skbb/

**Comment by wasikuss** [comment]
duplicate od #2 and already fixed with new css
