### ISSUE TITLE
Prevent return result on optgroups

### ISSUE THREAD

**Issue by jasonday** [wasikuss/select2-multi-checkboxes#7]
Using this select2 multi-checkboxes plugin, I commented out this line (too allow for typehead functionality):

which generates: https://jsfiddle.net/jasonday/hd6dqo4L/3/

Issue/question:

* When inputting a search term like "maine", how would I ensure that everything under the optgroup 'Maine' shows?

**Comment by wasikuss** [comment]
take a look into https://jsfiddle.net/wasikuss/u01zwzcs/
